import { Metadata } from "next";
import { ReactNode } from "react";
import { Container, Header } from "@/shared/components/shared";

export const metadata: Metadata = {
    title: "Just Pizza | Корзина",
    description: "Generated by aliens"
}

export default function CheckoutLayout({ children }: { children: ReactNode }) {
    return (
        <main className={"min-h-screen bg-[#F4F1EE]"}>
            <Container>
                <Header hasSearch={false} hasCart={false} className={"border-b-gray-200"}/>
                {children}
            </Container>
        </main>
    )
}